spring:
  application:
    name: irfanstore-logging-route-service
  profiles:
      active: cloud

server:
  error:
    whitelabel:
      enabled: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
